### ISSUE TITLE
Bot Crashes After Game Begins

### ISSUE THREAD

**Issue by Riotline** [denverquane/amongusdiscord#46] opened 2020-09-22 07:08 UTC
As the bot begins the muting process, the program/script crashes mid process. Restarting the program crashes if the game is still in progress

**Comment by denverquane** [comment] 2020-09-22 07:10
Hmm if you see this again, mind attaching log output, or a screenshot of the logs?

**Comment by Riotline** [comment] 2020-09-22 07:47
https://pastebin.com/9pdMjfFg

**Comment by athiwatc** [comment] 2020-09-22 19:35
There are some race condition happening.
A quick fix for me is to force `discordgo` library to be sync by adding `dg.SyncEvents = true` after the creation of the discord session in `bot.go`

**Comment by denverquane** [comment] 2020-09-22 19:37
Oh thanks for the heads up athi. I'm pretty sure this issue is fixed in prerelease 2.0.2 (with proper locking/unlocking of state to prevent race conditions in the underlying state data), but lmk if that doesn't seem to fix it.

**Comment by athiwatc** [comment] 2020-09-22 19:44
@denverquane Didn't see the updates, there are still possible race condition right now.
I will try to have a real game tomorrow and report back if it's still crashing.

**Comment by rorosaurus** [comment] 2020-09-22 22:22
I experienced this issue once earlier today with prerelease 2.0.2, but did not copy the log before trying to reproduce again.

IIRC the last message was `Successfully updated pendingVoice`, and it just hung there. The console stayed open, but the bot stopped replying on Discord, stopped muting, etc.

**Comment by denverquane** [comment] 2020-09-22 22:26
Hmmm doesn't sound like a crash, sounds like a deadlock. I'll investigate further

**Comment by rorosaurus** [comment] 2020-09-22 22:29
Yeah, sorry, I saw we were discussing race conditions in this issue so I figured it was relevant (since I assume it was probably stuck waiting for a semaphore).

**Comment by KMontag42** [comment] 2020-09-25 16:40
have you tried the newest release (2.0.5)? if you don't have this issue anymore please close this issue. thanks!

**Closed** 2020-10-02 18:34 UTC
Labels: info needed
