### ISSUE TITLE
[Feature Request] Dead players speak directly

### ISSUE THREAD

**Issue by fradali** [denverquane/amongusdiscord#118] opened 2020-10-07 00:40 UTC
Hello,

Is there any possibility when a player is dead, He can speak directly with other dead people and not wait for an Emergency call / find body ... then when game starts again he can talk to other.

Thanks.

**Comment by denverquane** [comment] 2020-10-07 00:43
Duplicate of https://github.com/denverquane/amongusdiscord/issues/83 but yes, this will be in the next update

**Closed by denverquane** 2020-10-07 00:43 UTC
