### ISSUE TITLE
emoji 

### ISSUE THREAD

**Issue by ShivamThakkar1** [denverquane/amongusdiscord#62] opened 2020-09-25 06:51 UTC
on my discord all emojis are already displayed as 1 even no one has yet reacted on it after reacting on it it changes to 2 and again one and reg player but in in starting its till 1 i dont know its bug or not but am facing this issue since few days also updated to latest version which is just added few hours ago

also new update with latest amonguscapture.exe when i input code among us discord says 
in error log 
2020/09/25 12:29:30 Detected transition to Menu; not doing anything about it yet

**Comment by KMontag42** [comment] 2020-09-25 16:28
this is not a bug, the bot puts each of the emojis onto the message for people to use. then once someone picks a color it removes their reaction as part of the normal flow.

README.md is your best friend.

closing.

**Closed by KMontag42** 2020-09-25 16:28 UTC

**Comment by ShivamThakkar1** [comment] 2020-09-25 16:56
am yes but without any input it displays 1 input

**Comment by itoncek4** [comment] 2020-10-16 09:36
Yes, because if you have zero reactions, the reaction disappears.
